### PR TITLE
[ENG-417] Check deploy commit descends from previous deploy commit

### PR DESCRIPTION
**Pull request by jkburges**
### High Level Description

Check deploy commit descends from previous deploy commit.

### Detailed Description

ENG-417

This ensures we only ever go forward (although a "break-glass" mechanism is provided just in case).

This changes removes checking against origin/main - somewhat unreliable and unnecessary with the above check in place - there is an assumption that only build server will be deploying and that it is configured to only run on the correct branch.

### Test Instructions

You can simulate past deploys having been done by manually updating the git sha in the [DDB table](https://console.aws.amazon.com/dynamodb/home?region=us-east-1#tables:selected=deploys;tab=items).

You may also like to test the break-glass parameter: either by adding to the pipeline.yml config or by setting an env var when initiating a build from the buildkite web UI.

### CODE REVIEW

**Comment by wbowling** [comment]
My linter is suggesting a few small changes:

```diff
diff --git a/hooks/post-command b/hooks/post-command
index 7aaf33f..73dd0d3 100755
--- a/hooks/post-command
+++ b/hooks/post-command
@@ -13,7 +13,7 @@ aws dynamodb put-item \
         \"BUILDKITE_COMMIT\": {\"S\": \"${BUILDKITE_COMMIT}\"}
       }"
 
-if [ ${BUILDKITE_COMMAND_EXIT_STATUS} -eq 0 ]; then
+if [ "${BUILDKITE_COMMAND_EXIT_STATUS}" -eq 0 ]; then
     notifySlack "$(getFinishMessage :shipit: succeeded)" "good"
 else
     notifySlack "$(getFinishMessage :warning: failed)" "danger"
diff --git a/hooks/pre-command b/hooks/pre-command
index d525cba..65f3798 100755
--- a/hooks/pre-command
+++ b/hooks/pre-command
@@ -7,12 +7,13 @@ DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
 
 notifySlack "$(getStartMessage)" warning
 
-export LAST_SUCCESSFUL_COMMIT=`aws dynamodb get-item --table-name deploys --key "{ \"BUILDKITE_PIPELINE_SLUG\": { \"S\": \"${BUILDKITE_PIPELINE_SLUG}\"}}" --projection-expression "BUILDKITE_COMMIT" --output text | cut -d $'\t' -f 2`
+LAST_SUCCESSFUL_COMMIT=$(aws dynamodb get-item --table-name deploys --key "{ \"BUILDKITE_PIPELINE_SLUG\": { \"S\": \"${BUILDKITE_PIPELINE_SLUG}\"}}" --projection-expression "BUILDKITE_COMMIT" --output text | cut -d $'\t' -f 2)
+export LAST_SUCCESSFUL_COMMIT
 
 if [ -z "$BUILDKITE_PLUGIN_DEPLOY_SKIP_GIT_CHECK" ]; then
     head_commit=$(git rev-parse HEAD)
 
-    if ! git merge-base --is-ancestor $LAST_SUCCESSFUL_COMMIT $head_commit; then
+    if ! git merge-base --is-ancestor "$LAST_SUCCESSFUL_COMMIT" "$head_commit"; then
         echo "$(tput setaf 1)Your commit ${head_commit} does not descend from previous deploy commit ${LAST_SUCCESSFUL_COMMIT}$(tput sgr 0)";
         notifySlack "$(getFinishMessage :warning: failed)" "danger"
         exit 1;

```

**Comment by wbowling** [comment]
I think with multiple PRs in this repo we might get into the situation where the "deployed" version is from one PR and then a different PR wont be a descend, since it deploys from all branches

**Comment by wbowling** [comment]
Yeah so https://buildkite.com/biteable/deploy-buildkite-plugin/builds/89 ran and set the latest to 07386400cacbfd350f1bda75f563ed72e8d1c2e2 (master -> ENG-417-check-descendant -> ENG-417-check-descendant-will1) and then https://buildkite.com/biteable/deploy-buildkite-plugin/builds/90 failed (master -> ENG-417-check-descendant -> ENG-417-check-descendant-will2) as it is not a descendant of ENG-417-check-descendant-will1

Anyway it's probably not going to happen very often, and the break-glass param worked https://buildkite.com/biteable/deploy-buildkite-plugin/builds/91 :D

**Comment by wbowling** [comment]
> ```diff
> -export LAST_SUCCESSFUL_COMMIT=`aws dynamodb get-item --table-name deploys --key "{ \"BUILDKITE_PIPELINE_SLUG\": { \"S\": \"${BUILDKITE_PIPELINE_SLUG}\"}}" --projection-expression "BUILDKITE_COMMIT" --output text | cut -d $'\t' -f 2`
> +LAST_SUCCESSFUL_COMMIT=$(aws dynamodb get-item --table-name deploys --key "{ \"BUILDKITE_PIPELINE_SLUG\": { \"S\": \"${BUILDKITE_PIPELINE_SLUG}\"}}" --projection-expression "BUILDKITE_COMMIT" --output text | cut -d $'\t' -f 2)
> +export LAST_SUCCESSFUL_COMMIT
> ```

It recommends doing this as otherwise the return code is from the `export` which is always true and masks any errors from the other command (so the `set -e` doesn't work as expected) https://github.com/koalaman/shellcheck/wiki/SC2155

**Comment by jkburges** [comment]
> I think with multiple PRs in this repo we might get into the situation where the "deployed" version is from one PR and then a different PR wont be a descend, since it deploys from all branches

Oh yeah that is a good point. Maybe this repo should have break glass set by default?

**Comment by jkburges** [comment]
> My linter is suggesting a few small changes:

I am always forgetting to quote variables in bash. Should we bring in shellcheck as a build check in this repo?

**Comment by wbowling** [comment]
> Oh yeah that is a good point. Maybe this repo should have break glass set by default?

Yeah that sounds good

> Should we bring in shellcheck as a build check in this repo?

That also sounds good, that's what rubymine has so will keep all the squiggles away

**Comment by wbowling** [comment]
> Should we bring in shellcheck as a build check in this repo?

Was this something you were planning for this PR? Otherwise everything looks good to go

**Comment by jkburges** [comment]
> Was this something you were planning for this PR? Otherwise everything looks good to go

I'll do it separately.

**Review by wbowling — CHANGES_REQUESTED** [review]
:shipit:

**Review by wbowling — APPROVED** [review]

**Comment by wbowling** [comment]
image

Oops, hit the wrong button and don't know how to remove it

**Pull request merged**
